version: '3'
services:
  laravel-voting-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    depends_on:
      - laravel-voting-db

  laravel-voting-db:
    image: mysql:5.7
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
