name: online-voting-app-workflow

on:
  push:
    branches: ["main", "5-question-entity"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_KEY: ${{secrets.APP_KEY}}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: ${{secrets.MYSQL_HOST}}
          MYSQL_DATABASE:  ${{secrets.MYSQL_DATABASE}}
          MYSQL_USERNAME:  ${{secrets.MYSQL_USERNAME}}
          MYSQL_ROOT_PASSWORD:  ${{secrets.MYSQL_PASSWORD}}
        ports:
          - "3306:3306"


    steps:
      - uses: actions/checkout@v3
  
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1-fpm-alpine"
      - name: install dependencies
        run: |
          composer install --no-scripts

      - name: Laravel initializing
        run: |
          echo "LS-ing::::"
          ls
          echo "***END of Lsing****"
          echo ${{secrets.APP_KEY}}
          cp .env* .env
          php artisan key:generate --env="prod"

      - name: Docker login
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/voting-app-image

      - name: push image to docker hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/voting-app-image

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
#      - name: Deploy action to heroku
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
#          appdir: "."













