name: online-voting-app-workflow

on:
  push:
    branches: ["main", "feature"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_KEY: ${{secrets.APP_KEY}}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: ${{secrets.MYSQL_HOST}}
          MYSQL_DATABASE:  ${{secrets.MYSQL_DATABASE}}
          MYSQL_USERNAME:  ${{secrets.MYSQL_USERNAME}}
          MYSQL_ROOT_PASSWORD:  ${{secrets.MYSQL_PASSWORD}}
        ports:
          - "3306:3306"


    steps:
      - uses: actions/checkout@v3
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1-fpm-alpine"
      - name: install dependencies
        run: |
          composer install --no-scripts

      - name: Laravel init
        run: |
          php artisan key:generate

      - name: build docker image and push to repo
        with:
          image:  ${{secrets.DOCKERHUB_USERNAME}}/votig-app-image
          tags: v1
          registery: docker.io
          dockerfile: Dockerfile
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}












